# Generated by Django 6.0.3 on 2026-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
