# Generated by Django 6.0.3 on 2026-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_tenant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
