# Generated by Django 6.0.3 on 2026-04-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_payment_payment_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
