# Generated by Django 6.0.3 on 2026-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_paymentallocation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice'),
        ),
    ]
