# Generated by Django 6.0.3 on 2026-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
