# Generated by Django 6.0.3 on 2026-04-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_lease_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='status',
        ),
    ]
