# Generated by Django 6.0.3 on 2026-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='base_rent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit_no_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit_type_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
