# Generated by Django 6.0.3 on 2026-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260415_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
